
package studentmanagementsystem;

import javax.swing.JOptionPane;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;


public class Dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());

   
    public Dashboard() {
        initComponents();
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/resources/icons/app.png"));
        setIconImage(icon.getImage());
        
        setLocationRelativeTo(null);
        setResizable(true);
        
        setTitle("Student Management System - Dashboard");
        
        showDate();
        
         welcome.setText("Welcome: " + Session.getFullName());

        if ("User".equalsIgnoreCase(Session.getRole())) {

            manageusers.setEnabled(false);

        } else {

            manageusers.setEnabled(true);

        }
         
    }
    
    public Dashboard(String fullname, String role) {

    initComponents();

    setLocationRelativeTo(null);
    setResizable(true);

    setTitle("Student Management System - Dashboard");

    showDate();

    welcome.setText("Welcome: " + fullname);

    if (role.equalsIgnoreCase("User")) {

        manageusers.setEnabled(false);

        }

    }
    
    private void showDate() {

    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

    date.setText(sdf.format(new Date()));

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        welcome = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        studentreg = new javax.swing.JButton();
        viewstudent = new javax.swing.JButton();
        manageusers = new javax.swing.JButton();
        reports = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(245, 245, 245));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(30, 58, 95));
        jLabel1.setText("STUDENT MANAGEMENT SYSTEM");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(52, 73, 94));
        jLabel2.setText("DASHBOARD");

        welcome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        welcome.setForeground(new java.awt.Color(204, 102, 0));
        welcome.setText("Welcome to the Dashboard!");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(60, 60, 60));
        jLabel4.setText("Date:");

        date.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        studentreg.setBackground(new java.awt.Color(41, 128, 185));
        studentreg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        studentreg.setForeground(new java.awt.Color(255, 255, 255));
        studentreg.setText("Student Registration");
        studentreg.addActionListener(this::studentregActionPerformed);

        viewstudent.setBackground(new java.awt.Color(41, 128, 185));
        viewstudent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        viewstudent.setForeground(new java.awt.Color(255, 255, 255));
        viewstudent.setText("View Students");
        viewstudent.addActionListener(this::viewstudentActionPerformed);

        manageusers.setBackground(new java.awt.Color(41, 128, 185));
        manageusers.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        manageusers.setForeground(new java.awt.Color(255, 255, 255));
        manageusers.setText("Manage Users");
        manageusers.addActionListener(this::manageusersActionPerformed);

        reports.setBackground(new java.awt.Color(41, 128, 185));
        reports.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        reports.setForeground(new java.awt.Color(255, 255, 255));
        reports.setText("Reports");
        reports.addActionListener(this::reportsActionPerformed);

        logout.setBackground(new java.awt.Color(52, 73, 94));
        logout.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Logout");
        logout.addActionListener(this::logoutActionPerformed);

        exit.setBackground(new java.awt.Color(192, 57, 43));
        exit.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("Exit");
        exit.addActionListener(this::exitActionPerformed);

        jLabel3.setText("Version 1.0 | © 2026 Student Management System");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(welcome)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(22, 22, 22))
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel3)
                    .addGap(28, 28, 28)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(240, 240, 240))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(logout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exit)
                .addGap(102, 102, 102))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(studentreg)
                            .addComponent(manageusers, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(126, 126, 126)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewstudent, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reports, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel1)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(welcome))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentreg)
                    .addComponent(viewstudent))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reports)
                    .addComponent(manageusers))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(exit)
                            .addComponent(logout))
                        .addContainerGap(73, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to logout?",
        "Logout Confirmation",
        JOptionPane.YES_NO_OPTION);

    if (option == JOptionPane.YES_OPTION) {

    Session.clearSession();
     
    Login login = new Login();
    login.setVisible(true);

    dispose();
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to exit the application?",
        "Exit Confirmation",
        JOptionPane.YES_NO_OPTION);

    if (option == JOptionPane.YES_OPTION) {
    System.exit(0);
        }
    }//GEN-LAST:event_exitActionPerformed

    private void studentregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentregActionPerformed
        // TODO add your handling code here:
        StudentForm student = new StudentForm();
        student.setVisible(true);
        dispose();
    }//GEN-LAST:event_studentregActionPerformed

    private void viewstudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewstudentActionPerformed
        // TODO add your handling code here:
        StudentForm student = new StudentForm();
        student.setVisible(true);
        dispose();
    }//GEN-LAST:event_viewstudentActionPerformed

    private void manageusersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageusersActionPerformed
        // TODO add your handling code here:
        UserManagement users = new UserManagement();
        users.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_manageusersActionPerformed

    private void reportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsActionPerformed
        // TODO add your handling code here:
        Reports report = new Reports();
        
        report.setVisible(true);
        dispose();
    }//GEN-LAST:event_reportsActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField date;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton logout;
    private javax.swing.JButton manageusers;
    private javax.swing.JButton reports;
    private javax.swing.JButton studentreg;
    private javax.swing.JButton viewstudent;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
