
package studentmanagementsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

//for printing on Java
import java.awt.print.PrinterException;

//for printing in pdf
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.pdf.PdfWriter;


import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.ImageIcon;


public class Reports extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Reports.class.getName());

    Connection cn;
    PreparedStatement pst;
    ResultSet rs;
    
    public Reports() {
        initComponents();
        
        setLocationRelativeTo(null);
        setResizable(false);

        myConnection();
        
        generateReport();
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/resources/icons/app.png"));
        setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        generate = new javax.swing.JButton();
        back = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        totalstudents = new javax.swing.JTextField();
        malestudents = new javax.swing.JTextField();
        femalestudents = new javax.swing.JTextField();
        activestudents = new javax.swing.JTextField();
        inactivestudents = new javax.swing.JTextField();
        totalfees = new javax.swing.JTextField();
        print = new javax.swing.JButton();
        exportpdf = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(245, 247, 250));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(30, 58, 95));
        jLabel2.setText("STUDENT MANAGEMENT SYSTEM");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(52, 73, 94));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/reports.png"))); // NOI18N
        jLabel3.setText("REPORTS");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(70, 70, 70));
        jLabel4.setText("Total Students: ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(70, 70, 70));
        jLabel5.setText("Male Students: ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(70, 70, 70));
        jLabel6.setText("Female Students: ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(70, 70, 70));
        jLabel7.setText("Active Students: ");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(70, 70, 70));
        jLabel8.setText("Inactive Students: ");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(70, 70, 70));
        jLabel9.setText("Total Fee Balance: ");

        generate.setBackground(new java.awt.Color(41, 128, 185));
        generate.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        generate.setForeground(new java.awt.Color(255, 255, 255));
        generate.setText("Generate Reports");
        generate.addActionListener(this::generateActionPerformed);

        back.setBackground(new java.awt.Color(52, 73, 94));
        back.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Back");
        back.addActionListener(this::backActionPerformed);

        refresh.setBackground(new java.awt.Color(52, 152, 219));
        refresh.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        refresh.setForeground(new java.awt.Color(255, 255, 255));
        refresh.setText("Refresh");
        refresh.addActionListener(this::refreshActionPerformed);

        totalstudents.setEditable(false);
        totalstudents.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        totalstudents.setForeground(new java.awt.Color(102, 102, 102));
        totalstudents.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        malestudents.setEditable(false);
        malestudents.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        malestudents.setForeground(new java.awt.Color(102, 102, 102));
        malestudents.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        femalestudents.setEditable(false);
        femalestudents.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        femalestudents.setForeground(new java.awt.Color(102, 102, 102));
        femalestudents.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        activestudents.setEditable(false);
        activestudents.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        activestudents.setForeground(new java.awt.Color(102, 102, 102));
        activestudents.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        inactivestudents.setEditable(false);
        inactivestudents.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inactivestudents.setForeground(new java.awt.Color(102, 102, 102));
        inactivestudents.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        totalfees.setEditable(false);
        totalfees.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        totalfees.setForeground(new java.awt.Color(102, 102, 102));
        totalfees.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        print.setBackground(new java.awt.Color(142, 68, 173));
        print.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        print.setForeground(new java.awt.Color(255, 255, 255));
        print.setText("Print Report");
        print.addActionListener(this::printActionPerformed);

        exportpdf.setBackground(new java.awt.Color(39, 174, 96));
        exportpdf.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        exportpdf.setForeground(new java.awt.Color(255, 255, 255));
        exportpdf.setText("Export PDF");
        exportpdf.addActionListener(this::exportpdfActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(433, 433, 433)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(generate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(print, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(totalstudents, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(malestudents, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(femalestudents, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(activestudents, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(inactivestudents, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(totalfees, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(refresh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(exportpdf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(38, 38, 38)
                                .addComponent(back))
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(jLabel3)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(totalstudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(malestudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(femalestudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(activestudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(inactivestudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(totalfees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generate)
                    .addComponent(refresh))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(exportpdf)
                            .addComponent(print))
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(back)
                        .addGap(14, 14, 14))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateActionPerformed
        // TODO add your handling code here:
        generateReport();
    }//GEN-LAST:event_generateActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
        refreshReport();
    }//GEN-LAST:event_refreshActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        Dashboard dashboard = new Dashboard();
        dashboard.setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
        printReport();
    }//GEN-LAST:event_printActionPerformed

    private void exportpdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportpdfActionPerformed
        // TODO add your handling code here:
        exportPDF();
    }//GEN-LAST:event_exportpdfActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Reports().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField activestudents;
    private javax.swing.JButton back;
    private javax.swing.JButton exportpdf;
    private javax.swing.JTextField femalestudents;
    private javax.swing.JButton generate;
    private javax.swing.JTextField inactivestudents;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField malestudents;
    private javax.swing.JButton print;
    private javax.swing.JButton refresh;
    private javax.swing.JTextField totalfees;
    private javax.swing.JTextField totalstudents;
    // End of variables declaration//GEN-END:variables

    private void myConnection() {

    try {

        cn = DriverManager.getConnection(
                "jdbc:mysql://localhost/student_management_system",
                "root",
                ""
        );

    } catch (SQLException ex) {

        JOptionPane.showMessageDialog(
                this,
                "Database Connection Failed!",
                "Error",
                JOptionPane.ERROR_MESSAGE
        );

        }

    }
    
    
   
    private void generateReport() {

    try {

        // Total Students
        pst = cn.prepareStatement("SELECT COUNT(*) FROM students");
        rs = pst.executeQuery();

        if (rs.next()) {
            totalstudents.setText(rs.getString(1));
        }

        // Male Students
        pst = cn.prepareStatement("SELECT COUNT(*) FROM students WHERE gender='Male'");
        rs = pst.executeQuery();

        if (rs.next()) {
            malestudents.setText(rs.getString(1));
        }

        // Female Students
        pst = cn.prepareStatement("SELECT COUNT(*) FROM students WHERE gender='Female'");
        rs = pst.executeQuery();

        if (rs.next()) {
            femalestudents.setText(rs.getString(1));
        }

        // Active Students
        pst = cn.prepareStatement("SELECT COUNT(*) FROM students WHERE status='Active'");
        rs = pst.executeQuery();

        if (rs.next()) {
            activestudents.setText(rs.getString(1));
        }

        // Inactive Students
        pst = cn.prepareStatement("SELECT COUNT(*) FROM students WHERE status='Inactive'");
        rs = pst.executeQuery();

        if (rs.next()) {
            inactivestudents.setText(rs.getString(1));
        }

        // Total Fee Balance
        pst = cn.prepareStatement("SELECT SUM(feebalance) FROM students");
        rs = pst.executeQuery();

        if (rs.next()) {

            double total = rs.getDouble(1);

            totalfees.setText(String.format("Ksh %.2f", total));

        }

    } catch (SQLException ex) {

        JOptionPane.showMessageDialog(this, ex.getMessage());

        }

    }
    
    
    private void printReport() {

    String report =
            "=============================================\n"
          + "      STUDENT MANAGEMENT SYSTEM REPORT\n"
          + "=============================================\n\n"

          + "Total Students      : " + totalstudents.getText() + "\n"
          + "Male Students       : " + malestudents.getText() + "\n"
          + "Female Students     : " + femalestudents.getText() + "\n"
          + "Active Students     : " + activestudents.getText() + "\n"
          + "Inactive Students   : " + inactivestudents.getText() + "\n"
          + "Total Fee Balance   : " + totalfees.getText() + "\n\n"

          + "=============================================\n"
          + "Generated by Student Management System\n"
          + "=============================================";

    javax.swing.JTextArea textArea = new javax.swing.JTextArea(report);

    try {

        textArea.print();

    } catch (PrinterException ex) {

        JOptionPane.showMessageDialog(this,
                "Printing failed.\n" + ex.getMessage());

        }

    }
    
    
    private void exportPDF() {

    Document document = new Document();

    try {

        PdfWriter.getInstance(document,
                new FileOutputStream("Student_Report.pdf"));

        document.open();

        Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18);
        Font headingFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14);
        Font bodyFont = FontFactory.getFont(FontFactory.HELVETICA, 12);

        Paragraph title = new Paragraph("STUDENT MANAGEMENT SYSTEM", titleFont);
        title.setAlignment(Paragraph.ALIGN_CENTER);

        document.add(title);
        document.add(new Paragraph(" "));
        document.add(new Paragraph("REPORT SUMMARY", headingFont));
        document.add(new Paragraph(" "));

        document.add(new Paragraph("Total Students : " + totalstudents.getText(), bodyFont));
        document.add(new Paragraph("Male Students : " + malestudents.getText(), bodyFont));
        document.add(new Paragraph("Female Students : " + femalestudents.getText(), bodyFont));
        document.add(new Paragraph("Active Students : " + activestudents.getText(), bodyFont));
        document.add(new Paragraph("Inactive Students : " + inactivestudents.getText(), bodyFont));
        document.add(new Paragraph("Total Fee Balance : " + totalfees.getText(), bodyFont));

        document.add(new Paragraph(" "));
        document.add(new Paragraph("Generated by Student Management System", headingFont));

        document.close();

        JOptionPane.showMessageDialog(this,
                "PDF exported successfully.\n\nSaved as Student_Report.pdf");

    } catch (DocumentException | IOException ex) {

        JOptionPane.showMessageDialog(this,
                ex.getMessage());

        }

    }
    

    private void refreshReport() {

    generateReport();

    }
}
