
package studentmanagementsystem;

import java.sql.Connection;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import java.awt.Image;


import javax.swing.table.DefaultTableModel;
import java.util.Vector;

public class StudentForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StudentForm.class.getName());

        Connection cn;
        PreparedStatement pst;
        ResultSet rs;
        
        String imagePath = "";
        
    public StudentForm() {
        initComponents();
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/resources/icons/app.png"));
        setIconImage(icon.getImage());
        
        studenttable.setSelectionBackground(Color.GREEN);
        studenttable.setSelectionForeground(Color.BLACK);
        
        setLocationRelativeTo(null);
        setResizable(true);

        myConnection();
        displayStudents();
        
        photo.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.BLACK));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        photobox = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        searchstudent = new javax.swing.JTextField();
        studentsearching = new javax.swing.JButton();
        browse = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        studenttable = new javax.swing.JTable();
        regnumber = new javax.swing.JTextField();
        firstname = new javax.swing.JTextField();
        lastname = new javax.swing.JTextField();
        gender = new javax.swing.JComboBox<>();
        course = new javax.swing.JComboBox<>();
        year = new javax.swing.JComboBox<>();
        phonenumber = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        feebalance = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        status = new javax.swing.JComboBox<>();
        photo = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(245, 247, 250));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(30, 58, 95));
        jLabel1.setText(" STUDENT MANAGEMENT SYSTEM ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(52, 73, 94));
        jLabel2.setText("STUDENT REGISTRATION ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(70, 70, 70));
        jLabel3.setText("Registration No:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(70, 70, 70));
        jLabel4.setText("First Name: ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(70, 70, 70));
        jLabel5.setText("Last Name:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(70, 70, 70));
        jLabel6.setText("Gender:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(70, 70, 70));
        jLabel7.setText("Course:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(70, 70, 70));
        jLabel8.setText("Year of Study:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(70, 70, 70));
        jLabel9.setText("Phone Number:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(70, 70, 70));
        jLabel10.setText("Email Address:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(70, 70, 70));
        jLabel11.setText("Fees Balance:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(70, 70, 70));
        jLabel12.setText("Status:");

        photobox.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        photobox.setForeground(new java.awt.Color(52, 73, 94));
        photobox.setText("Photo:");

        save.setBackground(new java.awt.Color(46, 204, 113));
        save.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setText("Save");
        save.addActionListener(this::saveActionPerformed);

        update.setBackground(new java.awt.Color(243, 156, 18));
        update.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("Update");
        update.addActionListener(this::updateActionPerformed);

        delete.setBackground(new java.awt.Color(231, 76, 60));
        delete.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("Delete");
        delete.addActionListener(this::deleteActionPerformed);

        clear.setBackground(new java.awt.Color(149, 165, 166));
        clear.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText("Clear");
        clear.addActionListener(this::clearActionPerformed);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(70, 70, 70));
        jLabel15.setText("Search by Registration Number:");

        searchstudent.setBackground(new java.awt.Color(245, 245, 245));
        searchstudent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchstudent.setForeground(new java.awt.Color(50, 50, 50));

        studentsearching.setBackground(new java.awt.Color(52, 152, 219));
        studentsearching.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        studentsearching.setForeground(new java.awt.Color(255, 255, 255));
        studentsearching.setText("Search");
        studentsearching.addActionListener(this::studentsearchingActionPerformed);

        browse.setBackground(new java.awt.Color(108, 117, 125));
        browse.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        browse.setForeground(new java.awt.Color(255, 255, 255));
        browse.setText("Browse");
        browse.addActionListener(this::browseActionPerformed);

        studenttable.setBackground(new java.awt.Color(52, 152, 219));
        studenttable.setForeground(new java.awt.Color(255, 255, 255));
        studenttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Reg No", "First Name", "Last Name", "Gender", "Course", "Year", "Phone", "Email", "Fees Balance", "Status"
            }
        ));
        studenttable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studenttableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(studenttable);

        regnumber.setBackground(new java.awt.Color(245, 245, 245));
        regnumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        regnumber.setForeground(new java.awt.Color(50, 50, 50));

        firstname.setBackground(new java.awt.Color(245, 245, 245));
        firstname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        firstname.setForeground(new java.awt.Color(50, 50, 50));

        lastname.setBackground(new java.awt.Color(245, 245, 245));
        lastname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lastname.setForeground(new java.awt.Color(50, 50, 50));

        gender.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gender.setForeground(new java.awt.Color(50, 50, 50));
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Male", "Female" }));
        gender.addItemListener(this::genderItemStateChanged);

        course.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        course.setForeground(new java.awt.Color(50, 50, 50));
        course.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "APT", "IST", "DSA", "SWE", "IBA", "IR", "ACC" }));

        year.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        year.setForeground(new java.awt.Color(50, 50, 50));
        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Year 1", "Year 2", "Year 3", "Year 4" }));

        phonenumber.setBackground(new java.awt.Color(245, 245, 245));
        phonenumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        phonenumber.setForeground(new java.awt.Color(50, 50, 50));

        email.setBackground(new java.awt.Color(245, 245, 245));
        email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        email.setForeground(new java.awt.Color(50, 50, 50));

        feebalance.setBackground(new java.awt.Color(245, 245, 245));
        feebalance.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        feebalance.setForeground(new java.awt.Color(50, 50, 50));

        jButton1.setBackground(new java.awt.Color(52, 73, 94));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        status.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        status.setForeground(new java.awt.Color(50, 50, 50));
        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive" }));

        photo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/user.png"))); // NOI18N

        jLabel13.setText("Version 1.0 | © 2026 Student Management System");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(photobox)
                        .addGap(30, 30, 30))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(phonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(feebalance, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(gender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(course, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(status, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(year, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(regnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(photo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(browse)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(save)
                                            .addGap(30, 30, 30)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(update)
                                            .addGap(42, 42, 42)
                                            .addComponent(delete))
                                        .addComponent(searchstudent))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(clear, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(studentsearching, javax.swing.GroupLayout.Alignment.TRAILING)))))
                        .addGap(0, 23, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(photobox))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(regnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(photo))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel12)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(course, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(phonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(feebalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clear)
                    .addComponent(delete)
                    .addComponent(update)
                    .addComponent(save)
                    .addComponent(browse))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(searchstudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentsearching))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jButton1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        addStudent();
    }//GEN-LAST:event_saveActionPerformed

    private void genderItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_genderItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_genderItemStateChanged

    private void studenttableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studenttableMouseClicked
        // TODO add your handling code here:

     int row = studenttable.getSelectedRow();

    // Create Student Object
    Student student = new Student();

    // Populate Student object from JTable
    student.setRegistrationNumber(studenttable.getValueAt(row, 0).toString());
    student.setFirstName(studenttable.getValueAt(row, 1).toString());
    student.setLastName(studenttable.getValueAt(row, 2).toString());
    student.setGender(studenttable.getValueAt(row, 3).toString());
    student.setCourse(studenttable.getValueAt(row, 4).toString());
    student.setYearLevel(studenttable.getValueAt(row, 5).toString());
    student.setPhone(studenttable.getValueAt(row, 6).toString());
    student.setEmail(studenttable.getValueAt(row, 7).toString());
    student.setFeeBalance(Double.parseDouble(studenttable.getValueAt(row, 8).toString()));
    student.setStatus(studenttable.getValueAt(row, 9).toString());

    // Display Student object on the form
    regnumber.setText(student.getRegistrationNumber());
    firstname.setText(student.getFirstName());
    lastname.setText(student.getLastName());
    gender.setSelectedItem(student.getGender());
    course.setSelectedItem(student.getCourse());
    year.setSelectedItem(student.getYearLevel());
    phonenumber.setText(student.getPhone());
    email.setText(student.getEmail());
    feebalance.setText(String.valueOf(student.getFeeBalance()));
    status.setSelectedItem(student.getStatus());

    // Prevent editing Registration Number
    regnumber.setEditable(false);

    try {

        pst = cn.prepareStatement(
                "SELECT photo FROM students WHERE registration_number=?");

        pst.setString(1, student.getRegistrationNumber());

        rs = pst.executeQuery();

        if (rs.next()) {

            student.setPhoto(rs.getString("photo"));

            imagePath = student.getPhoto();

            if (imagePath != null && !imagePath.isEmpty()) {

                ImageIcon icon = new ImageIcon(imagePath);

                Image img = icon.getImage().getScaledInstance(
                        photo.getWidth(),
                        photo.getHeight(),
                        Image.SCALE_SMOOTH);

                photo.setIcon(new ImageIcon(img));

            } else {

                photo.setIcon(null);

            }

            // Demonstrates Polymorphism
            System.out.println(student.getRole() + " selected.");

        }

    } catch (SQLException ex) {

        JOptionPane.showMessageDialog(this, ex.getMessage());

        }
    }//GEN-LAST:event_studenttableMouseClicked

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        updateStudent();
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        deleteStudent();
    }//GEN-LAST:event_deleteActionPerformed

    private void studentsearchingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentsearchingActionPerformed
        // TODO add your handling code here:
        searchStudent();
    }//GEN-LAST:event_studentsearchingActionPerformed

    private void browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseActionPerformed
        // TODO add your handling code here:
        browsePhoto();
    }//GEN-LAST:event_browseActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_clearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Dashboard dashboard = new Dashboard();
        
        dashboard.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StudentForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browse;
    private javax.swing.JButton clear;
    private javax.swing.JComboBox<String> course;
    private javax.swing.JButton delete;
    private javax.swing.JTextField email;
    private javax.swing.JTextField feebalance;
    private javax.swing.JTextField firstname;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastname;
    private javax.swing.JTextField phonenumber;
    private javax.swing.JLabel photo;
    private javax.swing.JLabel photobox;
    private javax.swing.JTextField regnumber;
    private javax.swing.JButton save;
    private javax.swing.JTextField searchstudent;
    private javax.swing.JComboBox<String> status;
    private javax.swing.JButton studentsearching;
    private javax.swing.JTable studenttable;
    private javax.swing.JButton update;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables

   private void myConnection() {

    try {

        cn = Database.connect();

    } catch (SQLException ex) {

        JOptionPane.showMessageDialog(
                this,
                "Database Connection Failed!",
                "Error",
                JOptionPane.ERROR_MESSAGE
        );

        }

    }
   
   
   private void addStudent() {

    if (!validateInputs()) {
        return;
    }
    
    Student student = new Student();

        student.setRegistrationNumber(regnumber.getText());
        student.setFirstName(firstname.getText());
        student.setLastName(lastname.getText());
        student.setGender(gender.getSelectedItem().toString());
        student.setCourse(course.getSelectedItem().toString());
        student.setYearLevel(year.getSelectedItem().toString());
        student.setPhone(phonenumber.getText());
        student.setEmail(email.getText());
        student.setFeeBalance(Double.parseDouble(feebalance.getText()));
        student.setStatus(status.getSelectedItem().toString());
        student.setPhoto(imagePath);

    try {

        // Check if Registration Number already exists
        pst = cn.prepareStatement(
                "SELECT registration_number FROM students WHERE registration_number=?");

        pst.setString(1, regnumber.getText());

        rs = pst.executeQuery();

        if (rs.next()) {

            JOptionPane.showMessageDialog(this,
                    "Registration Number already exists.");

            return;

        }

        // Insert New Student
        pst = cn.prepareStatement(
                "INSERT INTO students "
                + "(registration_number, first_name, last_name, gender, course, "
                + "year_level, phone, email, feebalance, status, photo) "
                + "VALUES (?,?,?,?,?,?,?,?,?,?,?)");

        pst.setString(1, student.getRegistrationNumber());
        pst.setString(2, firstname.getText());
        pst.setString(3, lastname.getText());
        pst.setString(4, gender.getSelectedItem().toString());
        pst.setString(5, course.getSelectedItem().toString());
        pst.setString(6, year.getSelectedItem().toString());
        pst.setString(7, phonenumber.getText());
        pst.setString(8, email.getText());
        pst.setDouble(9, Double.parseDouble(feebalance.getText()));
        pst.setString(10, status.getSelectedItem().toString());
        pst.setString(11, imagePath);

        pst.executeUpdate();

        JOptionPane.showMessageDialog(this,
                "Student Saved Successfully.");

        displayStudents();
        clear();

    } catch (SQLException ex) {

        JOptionPane.showMessageDialog(this, ex.getMessage());

     }

    }
   
   
   private void updateStudent() {

    if (!validateInputs()) {
        return;
    }
    
    Student student = new Student();

        student.setRegistrationNumber(regnumber.getText());
        student.setFirstName(firstname.getText());
        student.setLastName(lastname.getText());
        student.setGender(gender.getSelectedItem().toString());
        student.setCourse(course.getSelectedItem().toString());
        student.setYearLevel(year.getSelectedItem().toString());
        student.setPhone(phonenumber.getText());
        student.setEmail(email.getText());
        student.setFeeBalance(Double.parseDouble(feebalance.getText()));
        student.setStatus(status.getSelectedItem().toString());
        student.setPhoto(imagePath);

    try {

        pst = cn.prepareStatement(
                "UPDATE students SET "
                + "first_name=?, "
                + "last_name=?, "
                + "gender=?, "
                + "course=?, "
                + "year_level=?, "
                + "phone=?, "
                + "email=?, "
                + "feebalance=?, "
                + "status=?, "
                + "photo=? "
                + "WHERE registration_number=?");

        pst.setString(1, student.getFirstName());
        pst.setString(2, student.getLastName());
        pst.setString(3, student.getGender());
        pst.setString(4, student.getCourse());
        pst.setString(5, student.getYearLevel());
        pst.setString(6, student.getPhone());
        pst.setString(7, student.getEmail());
        pst.setDouble(8, student.getFeeBalance());
        pst.setString(9, student.getStatus());
        pst.setString(10, student.getPhoto());
        pst.setString(11, student.getRegistrationNumber());

        int rows = pst.executeUpdate();

        if (rows > 0) {

            JOptionPane.showMessageDialog(this,
                    "Student Updated Successfully.");

            displayStudents();
            clear();

        } else {

            JOptionPane.showMessageDialog(this,
                    "Student not found.");

        }

    } catch (SQLException ex) {

        JOptionPane.showMessageDialog(this, ex.getMessage());

        }

    }
   
   
   private void deleteStudent() {

    int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to delete this student?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {

        try {

            pst = cn.prepareStatement(
                    "DELETE FROM students WHERE registration_number=?");

            pst.setString(1, regnumber.getText());

            int rows = pst.executeUpdate();

            if (rows > 0) {

                JOptionPane.showMessageDialog(this,
                        "Student Deleted Successfully!");

                displayStudents();

                clear();

            } else {

                JOptionPane.showMessageDialog(this,
                        "Student Not Found.");

            }

        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(this,
                    ex.getMessage());

            }

        }

    }
   
   
   private void searchStudent() {

    try {

        pst = cn.prepareStatement(
                "SELECT * FROM students WHERE registration_number=?");

        pst.setString(1, searchstudent.getText());

        rs = pst.executeQuery();

        if (rs.next()) {

            // Create Student Object
            Student student = new Student();

            // Populate the object from the ResultSet
            student.setRegistrationNumber(rs.getString("registration_number"));
            student.setFirstName(rs.getString("first_name"));
            student.setLastName(rs.getString("last_name"));
            student.setGender(rs.getString("gender"));
            student.setCourse(rs.getString("course"));
            student.setYearLevel(rs.getString("year_level"));
            student.setPhone(rs.getString("phone"));
            student.setEmail(rs.getString("email"));
            student.setFeeBalance(rs.getDouble("feebalance"));
            student.setStatus(rs.getString("status"));
            student.setPhoto(rs.getString("photo"));

            // Populate the form using the Student object
            regnumber.setText(student.getRegistrationNumber());
            firstname.setText(student.getFirstName());
            lastname.setText(student.getLastName());
            gender.setSelectedItem(student.getGender());
            course.setSelectedItem(student.getCourse());
            year.setSelectedItem(student.getYearLevel());
            phonenumber.setText(student.getPhone());
            email.setText(student.getEmail());
            feebalance.setText(String.valueOf(student.getFeeBalance()));
            status.setSelectedItem(student.getStatus());

            imagePath = student.getPhoto();

            // Display photo
            if (imagePath != null && !imagePath.isEmpty()) {

                ImageIcon icon = new ImageIcon(imagePath);

                Image img = icon.getImage().getScaledInstance(
                        photo.getWidth(),
                        photo.getHeight(),
                        Image.SCALE_SMOOTH);

                photo.setIcon(new ImageIcon(img));

            } else {

                photo.setIcon(null);

            }

            regnumber.setEditable(false);

            // Highlight selected student in the table
            for (int i = 0; i < studenttable.getRowCount(); i++) {

                if (studenttable.getValueAt(i, 0).toString()
                        .equals(student.getRegistrationNumber())) {

                    studenttable.setRowSelectionInterval(i, i);

                    break;
                }
            }

            // Demonstrates Polymorphism
            System.out.println(student.getRole() + " record loaded successfully.");

        } else {

            JOptionPane.showMessageDialog(this,
                    "Student Not Found.");

        }

    } catch (SQLException ex) {

        JOptionPane.showMessageDialog(this,
                ex.getMessage());

    }
}
   
   
   private void browsePhoto() {

    JFileChooser chooser = new JFileChooser();

    int result = chooser.showOpenDialog(this);

    if (result == JFileChooser.APPROVE_OPTION) {

        File file = chooser.getSelectedFile();

        imagePath = file.getAbsolutePath();

        ImageIcon icon = new ImageIcon(imagePath);

        Image img = icon.getImage().getScaledInstance(
                photo.getWidth(),
                photo.getHeight(),
                Image.SCALE_SMOOTH);

        photo.setIcon(new ImageIcon(img));
        }
    }
   
  
   
   private boolean validateInputs() {

    if (regnumber.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Registration Number is required.");
        regnumber.requestFocus();
        return false;
    }

    if (firstname.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "First Name is required.");
        firstname.requestFocus();
        return false;
    }

    if (lastname.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Last Name is required.");
        lastname.requestFocus();
        return false;
    }

    if (gender.getSelectedIndex() == 0) {
        JOptionPane.showMessageDialog(this, "Please select Gender.");
        gender.requestFocus();
        return false;
    }

    if (course.getSelectedIndex() == 0) {
        JOptionPane.showMessageDialog(this, "Please select Course.");
        course.requestFocus();
        return false;
    }

    if (year.getSelectedIndex() == 0) {
        JOptionPane.showMessageDialog(this, "Please select Year Level.");
        year.requestFocus();
        return false;
    }

    if (phonenumber.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Phone Number is required.");
        phonenumber.requestFocus();
        return false;
    }

    if (!phonenumber.getText().matches("\\d{10}")) {
        JOptionPane.showMessageDialog(this,
                "Phone Number must contain exactly 10 digits.");
        phonenumber.requestFocus();
        return false;
    }

    if (email.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Email is required.");
        email.requestFocus();
        return false;
    }

    if (!email.getText().matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$")) {
        JOptionPane.showMessageDialog(this,
                "Enter a valid email address.");
        email.requestFocus();
        return false;
    }

    if (feebalance.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "Fee Balance is required.");
        feebalance.requestFocus();
        return false;
    }

    try {
        Double.parseDouble(feebalance.getText());

        if (Double.parseDouble(feebalance.getText()) < 0) {
            JOptionPane.showMessageDialog(this,
                    "Fee Balance cannot be negative.");
            feebalance.requestFocus();
            return false;
        }

    } catch (NumberFormatException ex) {

        JOptionPane.showMessageDialog(this,
                "Fee Balance must be numeric.");

        feebalance.requestFocus();

        return false;

    }

    return true;

    }

   
    private void clear() {

    // Clear text fields
    regnumber.setText("");
    firstname.setText("");
    lastname.setText("");
    phonenumber.setText("");
    email.setText("");
    feebalance.setText("");

    // Reset combo boxes
    gender.setSelectedIndex(0);
    course.setSelectedIndex(0);
    year.setSelectedIndex(0);
    status.setSelectedIndex(0);

    // Clear photo
    photo.setIcon(null);
    photo.setText("No Photo");    // Optional: remove if you don't use text on the label

    // Reset image path
    imagePath = "";

    // Make registration number editable again
    regnumber.setEditable(true);

    // Remove selected row in JTable
    studenttable.clearSelection();

    // Return cursor to first field
    regnumber.requestFocus();
    }

    private void displayStudents() {

    try {

        pst = cn.prepareStatement("SELECT * FROM students");

        rs = pst.executeQuery();

        DefaultTableModel model = (DefaultTableModel) studenttable.getModel();

        model.setRowCount(0);

        while (rs.next()) {

            Vector<Object> row = new Vector<>();

            row.add(rs.getString("registration_number"));
            row.add(rs.getString("first_name"));
            row.add(rs.getString("last_name"));
            row.add(rs.getString("gender"));
            row.add(rs.getString("course"));
            row.add(rs.getString("year_level"));
            row.add(rs.getString("phone"));
            row.add(rs.getString("email"));
            row.add(rs.getString("feebalance"));
            row.add(rs.getString("status"));

            model.addRow(row);

        }

    } catch (SQLException ex) {

        JOptionPane.showMessageDialog(this, ex.getMessage());

        }

    }
}
